/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentFiLending {
  export type AgentRepStruct = {
    score: BigNumberish;
    lastActivityAt: BigNumberish;
    totalLoans: BigNumberish;
    cleanRepayments: BigNumberish;
    defaults: BigNumberish;
  };

  export type AgentRepStructOutput = [
    score: bigint,
    lastActivityAt: bigint,
    totalLoans: bigint,
    cleanRepayments: bigint,
    defaults: bigint
  ] & {
    score: bigint;
    lastActivityAt: bigint;
    totalLoans: bigint;
    cleanRepayments: bigint;
    defaults: bigint;
  };

  export type LoanStruct = {
    loanId: BigNumberish;
    borrower: AddressLike;
    lender: AddressLike;
    principal: BigNumberish;
    collateral: BigNumberish;
    interestAmount: BigNumberish;
    dueAt: BigNumberish;
    repaidAt: BigNumberish;
    status: BigNumberish;
    borrowerEns: BytesLike;
    lenderEns: BytesLike;
  };

  export type LoanStructOutput = [
    loanId: bigint,
    borrower: string,
    lender: string,
    principal: bigint,
    collateral: bigint,
    interestAmount: bigint,
    dueAt: bigint,
    repaidAt: bigint,
    status: bigint,
    borrowerEns: string,
    lenderEns: string
  ] & {
    loanId: bigint;
    borrower: string;
    lender: string;
    principal: bigint;
    collateral: bigint;
    interestAmount: bigint;
    dueAt: bigint;
    repaidAt: bigint;
    status: bigint;
    borrowerEns: string;
    lenderEns: string;
  };
}

export interface AgentFiLendingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_GRACE"
      | "LOAN_DURATION"
      | "MAX_LOAN_USDC"
      | "MIN_LOAN_USDC"
      | "REP_MAX"
      | "REP_NEW_AGENT"
      | "REP_ZERO_COLLATERAL"
      | "USDC_DECIMALS"
      | "agentLoansAsBorrower"
      | "agentLoansAsLender"
      | "agentRep"
      | "fundLoan"
      | "getAgentRep"
      | "getBorrowerLoans"
      | "getLenderLoans"
      | "getLoan"
      | "liquidateLoan"
      | "loans"
      | "maxLoanSize"
      | "nextLoanId"
      | "owner"
      | "platformSigner"
      | "registerAgent"
      | "renounceOwnership"
      | "repayLoan"
      | "repayPartial"
      | "requestLoan"
      | "requiredCollateral"
      | "setPlatformSigner"
      | "setReputation"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "CollateralSeized"
      | "LoanDefaulted"
      | "LoanFunded"
      | "LoanRepaid"
      | "LoanRequested"
      | "OwnershipTransferred"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_GRACE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOAN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LOAN_USDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LOAN_USDC",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "REP_MAX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REP_NEW_AGENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REP_ZERO_COLLATERAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentLoansAsBorrower",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentLoansAsLender",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentRep",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentRep",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "maxLoanSize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextLoanId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayPartial",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredCollateral",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReputation",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_GRACE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOAN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LOAN_USDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LOAN_USDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "REP_MAX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REP_NEW_AGENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REP_ZERO_COLLATERAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDC_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentLoansAsBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentLoansAsLender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentRep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentRep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidateLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxLoanSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextLoanId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repayPartial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agent: AddressLike, initialScore: BigNumberish];
  export type OutputTuple = [agent: string, initialScore: bigint];
  export interface OutputObject {
    agent: string;
    initialScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralSeizedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    lender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [loanId: bigint, lender: string, amount: bigint];
  export interface OutputObject {
    loanId: bigint;
    lender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [loanId: BigNumberish, defaultedAt: BigNumberish];
  export type OutputTuple = [loanId: bigint, defaultedAt: bigint];
  export interface OutputObject {
    loanId: bigint;
    defaultedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFundedEvent {
  export type InputTuple = [loanId: BigNumberish, fundedAt: BigNumberish];
  export type OutputTuple = [loanId: bigint, fundedAt: bigint];
  export interface OutputObject {
    loanId: bigint;
    fundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    repaidAt: BigNumberish,
    withProfit: boolean
  ];
  export type OutputTuple = [
    loanId: bigint,
    repaidAt: bigint,
    withProfit: boolean
  ];
  export interface OutputObject {
    loanId: bigint;
    repaidAt: bigint;
    withProfit: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    lender: AddressLike,
    principal: BigNumberish,
    collateral: BigNumberish,
    interestAmount: BigNumberish,
    dueAt: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    lender: string,
    principal: bigint,
    collateral: bigint,
    interestAmount: bigint,
    dueAt: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    lender: string;
    principal: bigint;
    collateral: bigint;
    interestAmount: bigint;
    dueAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    agent: string,
    oldScore: bigint,
    newScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    agent: string;
    oldScore: bigint;
    newScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentFiLending extends BaseContract {
  connect(runner?: ContractRunner | null): AgentFiLending;
  waitForDeployment(): Promise<this>;

  interface: AgentFiLendingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_GRACE: TypedContractMethod<[], [bigint], "view">;

  LOAN_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_LOAN_USDC: TypedContractMethod<[], [bigint], "view">;

  MIN_LOAN_USDC: TypedContractMethod<[], [bigint], "view">;

  REP_MAX: TypedContractMethod<[], [bigint], "view">;

  REP_NEW_AGENT: TypedContractMethod<[], [bigint], "view">;

  REP_ZERO_COLLATERAL: TypedContractMethod<[], [bigint], "view">;

  USDC_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  agentLoansAsBorrower: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  agentLoansAsLender: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  agentRep: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        lastActivityAt: bigint;
        totalLoans: bigint;
        cleanRepayments: bigint;
        defaults: bigint;
      }
    ],
    "view"
  >;

  fundLoan: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  getAgentRep: TypedContractMethod<
    [agent: AddressLike],
    [AgentFiLending.AgentRepStructOutput],
    "view"
  >;

  getBorrowerLoans: TypedContractMethod<
    [agent: AddressLike],
    [bigint[]],
    "view"
  >;

  getLenderLoans: TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;

  getLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [AgentFiLending.LoanStructOutput],
    "view"
  >;

  liquidateLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        loanId: bigint;
        borrower: string;
        lender: string;
        principal: bigint;
        collateral: bigint;
        interestAmount: bigint;
        dueAt: bigint;
        repaidAt: bigint;
        status: bigint;
        borrowerEns: string;
        lenderEns: string;
      }
    ],
    "view"
  >;

  maxLoanSize: TypedContractMethod<[borrower: AddressLike], [bigint], "view">;

  nextLoanId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformSigner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [agent: AddressLike, initialScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayLoan: TypedContractMethod<
    [loanId: BigNumberish, profitGenerated: BigNumberish],
    [void],
    "nonpayable"
  >;

  repayPartial: TypedContractMethod<
    [loanId: BigNumberish, partialAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestLoan: TypedContractMethod<
    [
      borrower: AddressLike,
      lender: AddressLike,
      principal: BigNumberish,
      interestAmount: BigNumberish,
      borrowerEns: BytesLike,
      lenderEns: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  requiredCollateral: TypedContractMethod<
    [borrower: AddressLike, principal: BigNumberish],
    [bigint],
    "view"
  >;

  setPlatformSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setReputation: TypedContractMethod<
    [agent: AddressLike, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_GRACE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOAN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LOAN_USDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LOAN_USDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REP_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REP_NEW_AGENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REP_ZERO_COLLATERAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentLoansAsBorrower"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "agentLoansAsLender"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "agentRep"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        score: bigint;
        lastActivityAt: bigint;
        totalLoans: bigint;
        cleanRepayments: bigint;
        defaults: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentRep"
  ): TypedContractMethod<
    [agent: AddressLike],
    [AgentFiLending.AgentRepStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBorrowerLoans"
  ): TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLenderLoans"
  ): TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [AgentFiLending.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidateLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        loanId: bigint;
        borrower: string;
        lender: string;
        principal: bigint;
        collateral: bigint;
        interestAmount: bigint;
        dueAt: bigint;
        repaidAt: bigint;
        status: bigint;
        borrowerEns: string;
        lenderEns: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxLoanSize"
  ): TypedContractMethod<[borrower: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextLoanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agent: AddressLike, initialScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish, profitGenerated: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayPartial"
  ): TypedContractMethod<
    [loanId: BigNumberish, partialAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      lender: AddressLike,
      principal: BigNumberish,
      interestAmount: BigNumberish,
      borrowerEns: BytesLike,
      lenderEns: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requiredCollateral"
  ): TypedContractMethod<
    [borrower: AddressLike, principal: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPlatformSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReputation"
  ): TypedContractMethod<
    [agent: AddressLike, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CollateralSeized"
  ): TypedContractEvent<
    CollateralSeizedEvent.InputTuple,
    CollateralSeizedEvent.OutputTuple,
    CollateralSeizedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFunded"
  ): TypedContractEvent<
    LoanFundedEvent.InputTuple,
    LoanFundedEvent.OutputTuple,
    LoanFundedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,uint8)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "CollateralSeized(uint256,address,uint256)": TypedContractEvent<
      CollateralSeizedEvent.InputTuple,
      CollateralSeizedEvent.OutputTuple,
      CollateralSeizedEvent.OutputObject
    >;
    CollateralSeized: TypedContractEvent<
      CollateralSeizedEvent.InputTuple,
      CollateralSeizedEvent.OutputTuple,
      CollateralSeizedEvent.OutputObject
    >;

    "LoanDefaulted(uint256,uint256)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanFunded(uint256,uint256)": TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;
    LoanFunded: TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;

    "LoanRepaid(uint256,uint256,bool)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanRequested(uint256,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationUpdated(address,uint8,uint8,string)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
