/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentFiLending__factory } from "./AgentFiLending__factory";
export { MockERC20__factory } from "./MockERC20__factory";
